/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using iLoveVideoEditor.Sdk.Client;
using iLoveVideoEditor.Sdk.Model;

namespace iLoveVideoEditor.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAPIKeysApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create an API key
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <returns>ApiKeyWithSecret</returns>
        ApiKeyWithSecret CreateApiKey(CreateApiKeyRequest createApiKeyRequest);

        /// <summary>
        /// Create an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <returns>ApiResponse of ApiKeyWithSecret</returns>
        ApiResponse<ApiKeyWithSecret> CreateApiKeyWithHttpInfo(CreateApiKeyRequest createApiKeyRequest);
        /// <summary>
        /// Delete an API key
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UploadAsset200Response</returns>
        UploadAsset200Response DeleteApiKey(Guid id);

        /// <summary>
        /// Delete an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        ApiResponse<UploadAsset200Response> DeleteApiKeyWithHttpInfo(Guid id);
        /// <summary>
        /// List API keys
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListApiKeys200Response</returns>
        ListApiKeys200Response ListApiKeys();

        /// <summary>
        /// List API keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListApiKeys200Response</returns>
        ApiResponse<ListApiKeys200Response> ListApiKeysWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAPIKeysApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiKeyWithSecret</returns>
        System.Threading.Tasks.Task<ApiKeyWithSecret> CreateApiKeyAsync(CreateApiKeyRequest createApiKeyRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ApiKeyWithSecret)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiKeyWithSecret>> CreateApiKeyWithHttpInfoAsync(CreateApiKeyRequest createApiKeyRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        System.Threading.Tasks.Task<UploadAsset200Response> DeleteApiKeyAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UploadAsset200Response>> DeleteApiKeyWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List API keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListApiKeys200Response</returns>
        System.Threading.Tasks.Task<ListApiKeys200Response> ListApiKeysAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List API keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListApiKeys200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListApiKeys200Response>> ListApiKeysWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAPIKeysApi : IAPIKeysApiSync, IAPIKeysApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class APIKeysApi : IDisposable, IAPIKeysApi
    {
        private iLoveVideoEditor.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="APIKeysApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public APIKeysApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APIKeysApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public APIKeysApi(string basePath)
        {
            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APIKeysApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public APIKeysApi(iLoveVideoEditor.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APIKeysApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public APIKeysApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APIKeysApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public APIKeysApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APIKeysApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public APIKeysApi(HttpClient client, iLoveVideoEditor.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APIKeysApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public APIKeysApi(iLoveVideoEditor.Sdk.Client.ISynchronousClient client, iLoveVideoEditor.Sdk.Client.IAsynchronousClient asyncClient, iLoveVideoEditor.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public iLoveVideoEditor.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <returns>ApiKeyWithSecret</returns>
        public ApiKeyWithSecret CreateApiKey(CreateApiKeyRequest createApiKeyRequest)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ApiKeyWithSecret> localVarResponse = CreateApiKeyWithHttpInfo(createApiKeyRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <returns>ApiResponse of ApiKeyWithSecret</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<ApiKeyWithSecret> CreateApiKeyWithHttpInfo(CreateApiKeyRequest createApiKeyRequest)
        {
            // verify the required parameter 'createApiKeyRequest' is set
            if (createApiKeyRequest == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'createApiKeyRequest' when calling APIKeysApi->CreateApiKey");

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createApiKeyRequest;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ApiKeyWithSecret>("/v1/api-keys", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateApiKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiKeyWithSecret</returns>
        public async System.Threading.Tasks.Task<ApiKeyWithSecret> CreateApiKeyAsync(CreateApiKeyRequest createApiKeyRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ApiKeyWithSecret> localVarResponse = await CreateApiKeyWithHttpInfoAsync(createApiKeyRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ApiKeyWithSecret)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<ApiKeyWithSecret>> CreateApiKeyWithHttpInfoAsync(CreateApiKeyRequest createApiKeyRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createApiKeyRequest' is set
            if (createApiKeyRequest == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'createApiKeyRequest' when calling APIKeysApi->CreateApiKey");


            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createApiKeyRequest;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ApiKeyWithSecret>("/v1/api-keys", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateApiKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UploadAsset200Response</returns>
        public UploadAsset200Response DeleteApiKey(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = DeleteApiKeyWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> DeleteApiKeyWithHttpInfo(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<UploadAsset200Response>("/v1/api-keys/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteApiKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        public async System.Threading.Tasks.Task<UploadAsset200Response> DeleteApiKeyAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = await DeleteApiKeyWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete an API key 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response>> DeleteApiKeyWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<UploadAsset200Response>("/v1/api-keys/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteApiKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List API keys 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListApiKeys200Response</returns>
        public ListApiKeys200Response ListApiKeys()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListApiKeys200Response> localVarResponse = ListApiKeysWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List API keys 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListApiKeys200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<ListApiKeys200Response> ListApiKeysWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListApiKeys200Response>("/v1/api-keys", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListApiKeys", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List API keys 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListApiKeys200Response</returns>
        public async System.Threading.Tasks.Task<ListApiKeys200Response> ListApiKeysAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListApiKeys200Response> localVarResponse = await ListApiKeysWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List API keys 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListApiKeys200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<ListApiKeys200Response>> ListApiKeysWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListApiKeys200Response>("/v1/api-keys", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListApiKeys", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
