/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using iLoveVideoEditor.Sdk.Client;
using iLoveVideoEditor.Sdk.Model;

namespace iLoveVideoEditor.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBillingApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Cancel active subscription
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>UploadAsset200Response</returns>
        UploadAsset200Response CancelSubscription();

        /// <summary>
        /// Cancel active subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        ApiResponse<UploadAsset200Response> CancelSubscriptionWithHttpInfo();
        /// <summary>
        /// Create checkout session
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <returns>CreateCheckoutSession200Response</returns>
        CreateCheckoutSession200Response CreateCheckoutSession(CreateCheckoutSessionRequest createCheckoutSessionRequest);

        /// <summary>
        /// Create checkout session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <returns>ApiResponse of CreateCheckoutSession200Response</returns>
        ApiResponse<CreateCheckoutSession200Response> CreateCheckoutSessionWithHttpInfo(CreateCheckoutSessionRequest createCheckoutSessionRequest);
        /// <summary>
        /// Get credit balance and history
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreditBalance</returns>
        CreditBalance GetCredits();

        /// <summary>
        /// Get credit balance and history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreditBalance</returns>
        ApiResponse<CreditBalance> GetCreditsWithHttpInfo();
        /// <summary>
        /// Get subscription
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetSubscription200Response</returns>
        GetSubscription200Response GetSubscription();

        /// <summary>
        /// Get subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetSubscription200Response</returns>
        ApiResponse<GetSubscription200Response> GetSubscriptionWithHttpInfo();
        /// <summary>
        /// Get usage log history
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <returns>GetUsage200Response</returns>
        GetUsage200Response GetUsage(int? limit = default, string? type = default);

        /// <summary>
        /// Get usage log history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <returns>ApiResponse of GetUsage200Response</returns>
        ApiResponse<GetUsage200Response> GetUsageWithHttpInfo(int? limit = default, string? type = default);
        /// <summary>
        /// List invoices
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListInvoices200Response</returns>
        ListInvoices200Response ListInvoices();

        /// <summary>
        /// List invoices
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListInvoices200Response</returns>
        ApiResponse<ListInvoices200Response> ListInvoicesWithHttpInfo();
        /// <summary>
        /// List available prices
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>BillingPrices</returns>
        BillingPrices ListPrices();

        /// <summary>
        /// List available prices
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of BillingPrices</returns>
        ApiResponse<BillingPrices> ListPricesWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBillingApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Cancel active subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        System.Threading.Tasks.Task<UploadAsset200Response> CancelSubscriptionAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Cancel active subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UploadAsset200Response>> CancelSubscriptionWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create checkout session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateCheckoutSession200Response</returns>
        System.Threading.Tasks.Task<CreateCheckoutSession200Response> CreateCheckoutSessionAsync(CreateCheckoutSessionRequest createCheckoutSessionRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create checkout session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateCheckoutSession200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateCheckoutSession200Response>> CreateCheckoutSessionWithHttpInfoAsync(CreateCheckoutSessionRequest createCheckoutSessionRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get credit balance and history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreditBalance</returns>
        System.Threading.Tasks.Task<CreditBalance> GetCreditsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get credit balance and history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreditBalance)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreditBalance>> GetCreditsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetSubscription200Response</returns>
        System.Threading.Tasks.Task<GetSubscription200Response> GetSubscriptionAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetSubscription200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetSubscription200Response>> GetSubscriptionWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get usage log history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUsage200Response</returns>
        System.Threading.Tasks.Task<GetUsage200Response> GetUsageAsync(int? limit = default, string? type = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get usage log history
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUsage200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetUsage200Response>> GetUsageWithHttpInfoAsync(int? limit = default, string? type = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List invoices
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListInvoices200Response</returns>
        System.Threading.Tasks.Task<ListInvoices200Response> ListInvoicesAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List invoices
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListInvoices200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListInvoices200Response>> ListInvoicesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List available prices
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingPrices</returns>
        System.Threading.Tasks.Task<BillingPrices> ListPricesAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List available prices
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingPrices)</returns>
        System.Threading.Tasks.Task<ApiResponse<BillingPrices>> ListPricesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBillingApi : IBillingApiSync, IBillingApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BillingApi : IDisposable, IBillingApi
    {
        private iLoveVideoEditor.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public BillingApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public BillingApi(string basePath)
        {
            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public BillingApi(iLoveVideoEditor.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public BillingApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public BillingApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public BillingApi(HttpClient client, iLoveVideoEditor.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public BillingApi(iLoveVideoEditor.Sdk.Client.ISynchronousClient client, iLoveVideoEditor.Sdk.Client.IAsynchronousClient asyncClient, iLoveVideoEditor.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public iLoveVideoEditor.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Cancel active subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>UploadAsset200Response</returns>
        public UploadAsset200Response CancelSubscription()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = CancelSubscriptionWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel active subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> CancelSubscriptionWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<UploadAsset200Response>("/billing/cancel", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CancelSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Cancel active subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        public async System.Threading.Tasks.Task<UploadAsset200Response> CancelSubscriptionAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = await CancelSubscriptionWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel active subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response>> CancelSubscriptionWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<UploadAsset200Response>("/billing/cancel", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CancelSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create checkout session 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <returns>CreateCheckoutSession200Response</returns>
        public CreateCheckoutSession200Response CreateCheckoutSession(CreateCheckoutSessionRequest createCheckoutSessionRequest)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreateCheckoutSession200Response> localVarResponse = CreateCheckoutSessionWithHttpInfo(createCheckoutSessionRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create checkout session 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <returns>ApiResponse of CreateCheckoutSession200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<CreateCheckoutSession200Response> CreateCheckoutSessionWithHttpInfo(CreateCheckoutSessionRequest createCheckoutSessionRequest)
        {
            // verify the required parameter 'createCheckoutSessionRequest' is set
            if (createCheckoutSessionRequest == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'createCheckoutSessionRequest' when calling BillingApi->CreateCheckoutSession");

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createCheckoutSessionRequest;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateCheckoutSession200Response>("/billing/checkout", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCheckoutSession", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create checkout session 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateCheckoutSession200Response</returns>
        public async System.Threading.Tasks.Task<CreateCheckoutSession200Response> CreateCheckoutSessionAsync(CreateCheckoutSessionRequest createCheckoutSessionRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreateCheckoutSession200Response> localVarResponse = await CreateCheckoutSessionWithHttpInfoAsync(createCheckoutSessionRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create checkout session 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createCheckoutSessionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateCheckoutSession200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<CreateCheckoutSession200Response>> CreateCheckoutSessionWithHttpInfoAsync(CreateCheckoutSessionRequest createCheckoutSessionRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createCheckoutSessionRequest' is set
            if (createCheckoutSessionRequest == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'createCheckoutSessionRequest' when calling BillingApi->CreateCheckoutSession");


            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createCheckoutSessionRequest;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateCheckoutSession200Response>("/billing/checkout", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCheckoutSession", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get credit balance and history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreditBalance</returns>
        public CreditBalance GetCredits()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreditBalance> localVarResponse = GetCreditsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get credit balance and history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreditBalance</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<CreditBalance> GetCreditsWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CreditBalance>("/billing/credits", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCredits", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get credit balance and history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreditBalance</returns>
        public async System.Threading.Tasks.Task<CreditBalance> GetCreditsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreditBalance> localVarResponse = await GetCreditsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get credit balance and history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreditBalance)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<CreditBalance>> GetCreditsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CreditBalance>("/billing/credits", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCredits", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetSubscription200Response</returns>
        public GetSubscription200Response GetSubscription()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetSubscription200Response> localVarResponse = GetSubscriptionWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetSubscription200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<GetSubscription200Response> GetSubscriptionWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetSubscription200Response>("/billing/subscription", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetSubscription200Response</returns>
        public async System.Threading.Tasks.Task<GetSubscription200Response> GetSubscriptionAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetSubscription200Response> localVarResponse = await GetSubscriptionWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetSubscription200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<GetSubscription200Response>> GetSubscriptionWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetSubscription200Response>("/billing/subscription", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get usage log history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <returns>GetUsage200Response</returns>
        public GetUsage200Response GetUsage(int? limit = default, string? type = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetUsage200Response> localVarResponse = GetUsageWithHttpInfo(limit, type);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get usage log history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <returns>ApiResponse of GetUsage200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<GetUsage200Response> GetUsageWithHttpInfo(int? limit = default, string? type = default)
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetUsage200Response>("/billing/usage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUsage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get usage log history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUsage200Response</returns>
        public async System.Threading.Tasks.Task<GetUsage200Response> GetUsageAsync(int? limit = default, string? type = default, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetUsage200Response> localVarResponse = await GetUsageWithHttpInfoAsync(limit, type, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get usage log history 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 30)</param>
        /// <param name="type"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUsage200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<GetUsage200Response>> GetUsageWithHttpInfoAsync(int? limit = default, string? type = default, System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetUsage200Response>("/billing/usage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUsage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List invoices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListInvoices200Response</returns>
        public ListInvoices200Response ListInvoices()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListInvoices200Response> localVarResponse = ListInvoicesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List invoices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListInvoices200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<ListInvoices200Response> ListInvoicesWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListInvoices200Response>("/billing/invoices", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListInvoices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List invoices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListInvoices200Response</returns>
        public async System.Threading.Tasks.Task<ListInvoices200Response> ListInvoicesAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListInvoices200Response> localVarResponse = await ListInvoicesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List invoices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListInvoices200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<ListInvoices200Response>> ListInvoicesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListInvoices200Response>("/billing/invoices", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListInvoices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List available prices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>BillingPrices</returns>
        public BillingPrices ListPrices()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<BillingPrices> localVarResponse = ListPricesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List available prices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of BillingPrices</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<BillingPrices> ListPricesWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<BillingPrices>("/billing/prices", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPrices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List available prices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingPrices</returns>
        public async System.Threading.Tasks.Task<BillingPrices> ListPricesAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<BillingPrices> localVarResponse = await ListPricesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List available prices 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingPrices)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<BillingPrices>> ListPricesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<BillingPrices>("/billing/prices", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPrices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
