/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using iLoveVideoEditor.Sdk.Client;
using iLoveVideoEditor.Sdk.Model;

namespace iLoveVideoEditor.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntegrationsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a workspace integration
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>CreateIntegration201Response</returns>
        CreateIntegration201Response CreateIntegration(WorkspaceIntegrationInput workspaceIntegrationInput);

        /// <summary>
        /// Create a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>ApiResponse of CreateIntegration201Response</returns>
        ApiResponse<CreateIntegration201Response> CreateIntegrationWithHttpInfo(WorkspaceIntegrationInput workspaceIntegrationInput);
        /// <summary>
        /// Delete default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>UploadAsset200Response</returns>
        UploadAsset200Response DeleteDestination();

        /// <summary>
        /// Delete default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        ApiResponse<UploadAsset200Response> DeleteDestinationWithHttpInfo();
        /// <summary>
        /// Delete a workspace integration
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UploadAsset200Response</returns>
        UploadAsset200Response DeleteIntegration(Guid id);

        /// <summary>
        /// Delete a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        ApiResponse<UploadAsset200Response> DeleteIntegrationWithHttpInfo(Guid id);
        /// <summary>
        /// Get default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetDestination200Response</returns>
        GetDestination200Response GetDestination();

        /// <summary>
        /// Get default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetDestination200Response</returns>
        ApiResponse<GetDestination200Response> GetDestinationWithHttpInfo();
        /// <summary>
        /// List workspace storage integrations
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListIntegrations200Response</returns>
        ListIntegrations200Response ListIntegrations();

        /// <summary>
        /// List workspace storage integrations
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListIntegrations200Response</returns>
        ApiResponse<ListIntegrations200Response> ListIntegrationsWithHttpInfo();
        /// <summary>
        /// Set default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>GetDestination200Response</returns>
        GetDestination200Response SetDestination(DestinationInput destinationInput);

        /// <summary>
        /// Set default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>ApiResponse of GetDestination200Response</returns>
        ApiResponse<GetDestination200Response> SetDestinationWithHttpInfo(DestinationInput destinationInput);
        /// <summary>
        /// Test default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination test endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>TestIntegration200Response</returns>
        TestIntegration200Response TestDestination(DestinationInput destinationInput);

        /// <summary>
        /// Test default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination test endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>ApiResponse of TestIntegration200Response</returns>
        ApiResponse<TestIntegration200Response> TestDestinationWithHttpInfo(DestinationInput destinationInput);
        /// <summary>
        /// Test a workspace integration
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>TestIntegration200Response</returns>
        TestIntegration200Response TestIntegration(Guid id);

        /// <summary>
        /// Test a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of TestIntegration200Response</returns>
        ApiResponse<TestIntegration200Response> TestIntegrationWithHttpInfo(Guid id);
        /// <summary>
        /// Update a workspace integration
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>CreateIntegration201Response</returns>
        CreateIntegration201Response UpdateIntegration(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput);

        /// <summary>
        /// Update a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>ApiResponse of CreateIntegration201Response</returns>
        ApiResponse<CreateIntegration201Response> UpdateIntegrationWithHttpInfo(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntegrationsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateIntegration201Response</returns>
        System.Threading.Tasks.Task<CreateIntegration201Response> CreateIntegrationAsync(WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateIntegration201Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateIntegration201Response>> CreateIntegrationWithHttpInfoAsync(WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        System.Threading.Tasks.Task<UploadAsset200Response> DeleteDestinationAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UploadAsset200Response>> DeleteDestinationWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        System.Threading.Tasks.Task<UploadAsset200Response> DeleteIntegrationAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UploadAsset200Response>> DeleteIntegrationWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetDestination200Response</returns>
        System.Threading.Tasks.Task<GetDestination200Response> GetDestinationAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetDestination200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetDestination200Response>> GetDestinationWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List workspace storage integrations
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListIntegrations200Response</returns>
        System.Threading.Tasks.Task<ListIntegrations200Response> ListIntegrationsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List workspace storage integrations
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListIntegrations200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListIntegrations200Response>> ListIntegrationsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Set default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetDestination200Response</returns>
        System.Threading.Tasks.Task<GetDestination200Response> SetDestinationAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Set default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetDestination200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetDestination200Response>> SetDestinationWithHttpInfoAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Test default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination test endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TestIntegration200Response</returns>
        System.Threading.Tasks.Task<TestIntegration200Response> TestDestinationAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Test default destination
        /// </summary>
        /// <remarks>
        /// Backwards-compatible single-destination test endpoint.
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TestIntegration200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<TestIntegration200Response>> TestDestinationWithHttpInfoAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Test a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TestIntegration200Response</returns>
        System.Threading.Tasks.Task<TestIntegration200Response> TestIntegrationAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Test a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TestIntegration200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<TestIntegration200Response>> TestIntegrationWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateIntegration201Response</returns>
        System.Threading.Tasks.Task<CreateIntegration201Response> UpdateIntegrationAsync(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update a workspace integration
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateIntegration201Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateIntegration201Response>> UpdateIntegrationWithHttpInfoAsync(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIntegrationsApi : IIntegrationsApiSync, IIntegrationsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class IntegrationsApi : IDisposable, IIntegrationsApi
    {
        private iLoveVideoEditor.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public IntegrationsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public IntegrationsApi(string basePath)
        {
            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public IntegrationsApi(iLoveVideoEditor.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public IntegrationsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public IntegrationsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public IntegrationsApi(HttpClient client, iLoveVideoEditor.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public IntegrationsApi(iLoveVideoEditor.Sdk.Client.ISynchronousClient client, iLoveVideoEditor.Sdk.Client.IAsynchronousClient asyncClient, iLoveVideoEditor.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public iLoveVideoEditor.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>CreateIntegration201Response</returns>
        public CreateIntegration201Response CreateIntegration(WorkspaceIntegrationInput workspaceIntegrationInput)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response> localVarResponse = CreateIntegrationWithHttpInfo(workspaceIntegrationInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>ApiResponse of CreateIntegration201Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response> CreateIntegrationWithHttpInfo(WorkspaceIntegrationInput workspaceIntegrationInput)
        {
            // verify the required parameter 'workspaceIntegrationInput' is set
            if (workspaceIntegrationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'workspaceIntegrationInput' when calling IntegrationsApi->CreateIntegration");

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = workspaceIntegrationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateIntegration201Response>("/v1/integrations", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateIntegration201Response</returns>
        public async System.Threading.Tasks.Task<CreateIntegration201Response> CreateIntegrationAsync(WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response> localVarResponse = await CreateIntegrationWithHttpInfoAsync(workspaceIntegrationInput, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateIntegration201Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response>> CreateIntegrationWithHttpInfoAsync(WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'workspaceIntegrationInput' is set
            if (workspaceIntegrationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'workspaceIntegrationInput' when calling IntegrationsApi->CreateIntegration");


            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = workspaceIntegrationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateIntegration201Response>("/v1/integrations", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>UploadAsset200Response</returns>
        public UploadAsset200Response DeleteDestination()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = DeleteDestinationWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> DeleteDestinationWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<UploadAsset200Response>("/v1/destination", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        public async System.Threading.Tasks.Task<UploadAsset200Response> DeleteDestinationAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = await DeleteDestinationWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response>> DeleteDestinationWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<UploadAsset200Response>("/v1/destination", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UploadAsset200Response</returns>
        public UploadAsset200Response DeleteIntegration(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = DeleteIntegrationWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> DeleteIntegrationWithHttpInfo(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<UploadAsset200Response>("/v1/integrations/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        public async System.Threading.Tasks.Task<UploadAsset200Response> DeleteIntegrationAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = await DeleteIntegrationWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response>> DeleteIntegrationWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<UploadAsset200Response>("/v1/integrations/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetDestination200Response</returns>
        public GetDestination200Response GetDestination()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response> localVarResponse = GetDestinationWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetDestination200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response> GetDestinationWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetDestination200Response>("/v1/destination", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetDestination200Response</returns>
        public async System.Threading.Tasks.Task<GetDestination200Response> GetDestinationAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response> localVarResponse = await GetDestinationWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetDestination200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response>> GetDestinationWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetDestination200Response>("/v1/destination", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List workspace storage integrations 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListIntegrations200Response</returns>
        public ListIntegrations200Response ListIntegrations()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListIntegrations200Response> localVarResponse = ListIntegrationsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List workspace storage integrations 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListIntegrations200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<ListIntegrations200Response> ListIntegrationsWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListIntegrations200Response>("/v1/integrations", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListIntegrations", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List workspace storage integrations 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListIntegrations200Response</returns>
        public async System.Threading.Tasks.Task<ListIntegrations200Response> ListIntegrationsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListIntegrations200Response> localVarResponse = await ListIntegrationsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List workspace storage integrations 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListIntegrations200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<ListIntegrations200Response>> ListIntegrationsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListIntegrations200Response>("/v1/integrations", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListIntegrations", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Set default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>GetDestination200Response</returns>
        public GetDestination200Response SetDestination(DestinationInput destinationInput)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response> localVarResponse = SetDestinationWithHttpInfo(destinationInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>ApiResponse of GetDestination200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response> SetDestinationWithHttpInfo(DestinationInput destinationInput)
        {
            // verify the required parameter 'destinationInput' is set
            if (destinationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'destinationInput' when calling IntegrationsApi->SetDestination");

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = destinationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<GetDestination200Response>("/v1/destination", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Set default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetDestination200Response</returns>
        public async System.Threading.Tasks.Task<GetDestination200Response> SetDestinationAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response> localVarResponse = await SetDestinationWithHttpInfoAsync(destinationInput, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set default destination Backwards-compatible single-destination endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetDestination200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<GetDestination200Response>> SetDestinationWithHttpInfoAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'destinationInput' is set
            if (destinationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'destinationInput' when calling IntegrationsApi->SetDestination");


            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = destinationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<GetDestination200Response>("/v1/destination", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Test default destination Backwards-compatible single-destination test endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>TestIntegration200Response</returns>
        public TestIntegration200Response TestDestination(DestinationInput destinationInput)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response> localVarResponse = TestDestinationWithHttpInfo(destinationInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test default destination Backwards-compatible single-destination test endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <returns>ApiResponse of TestIntegration200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response> TestDestinationWithHttpInfo(DestinationInput destinationInput)
        {
            // verify the required parameter 'destinationInput' is set
            if (destinationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'destinationInput' when calling IntegrationsApi->TestDestination");

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = destinationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TestIntegration200Response>("/v1/destination/test", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Test default destination Backwards-compatible single-destination test endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TestIntegration200Response</returns>
        public async System.Threading.Tasks.Task<TestIntegration200Response> TestDestinationAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response> localVarResponse = await TestDestinationWithHttpInfoAsync(destinationInput, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test default destination Backwards-compatible single-destination test endpoint.
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="destinationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TestIntegration200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response>> TestDestinationWithHttpInfoAsync(DestinationInput destinationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'destinationInput' is set
            if (destinationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'destinationInput' when calling IntegrationsApi->TestDestination");


            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = destinationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<TestIntegration200Response>("/v1/destination/test", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestDestination", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Test a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>TestIntegration200Response</returns>
        public TestIntegration200Response TestIntegration(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response> localVarResponse = TestIntegrationWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of TestIntegration200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response> TestIntegrationWithHttpInfo(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TestIntegration200Response>("/v1/integrations/{id}/test", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Test a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TestIntegration200Response</returns>
        public async System.Threading.Tasks.Task<TestIntegration200Response> TestIntegrationAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response> localVarResponse = await TestIntegrationWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Test a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TestIntegration200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<TestIntegration200Response>> TestIntegrationWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<TestIntegration200Response>("/v1/integrations/{id}/test", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TestIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>CreateIntegration201Response</returns>
        public CreateIntegration201Response UpdateIntegration(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response> localVarResponse = UpdateIntegrationWithHttpInfo(id, workspaceIntegrationInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <returns>ApiResponse of CreateIntegration201Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response> UpdateIntegrationWithHttpInfo(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput)
        {
            // verify the required parameter 'workspaceIntegrationInput' is set
            if (workspaceIntegrationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'workspaceIntegrationInput' when calling IntegrationsApi->UpdateIntegration");

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = workspaceIntegrationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<CreateIntegration201Response>("/v1/integrations/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateIntegration201Response</returns>
        public async System.Threading.Tasks.Task<CreateIntegration201Response> UpdateIntegrationAsync(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response> localVarResponse = await UpdateIntegrationWithHttpInfoAsync(id, workspaceIntegrationInput, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update a workspace integration 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="workspaceIntegrationInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateIntegration201Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<CreateIntegration201Response>> UpdateIntegrationWithHttpInfoAsync(Guid id, WorkspaceIntegrationInput workspaceIntegrationInput, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'workspaceIntegrationInput' is set
            if (workspaceIntegrationInput == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'workspaceIntegrationInput' when calling IntegrationsApi->UpdateIntegration");


            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = workspaceIntegrationInput;

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<CreateIntegration201Response>("/v1/integrations/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateIntegration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
