/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using iLoveVideoEditor.Sdk.Client;
using iLoveVideoEditor.Sdk.Model;

namespace iLoveVideoEditor.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a webhook subscription
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <returns>WebhookSubscription</returns>
        WebhookSubscription CreateWebhookSubscription(WebhookSubscriptionCreate webhookSubscriptionCreate);

        /// <summary>
        /// Create a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <returns>ApiResponse of WebhookSubscription</returns>
        ApiResponse<WebhookSubscription> CreateWebhookSubscriptionWithHttpInfo(WebhookSubscriptionCreate webhookSubscriptionCreate);
        /// <summary>
        /// Revoke a webhook subscription
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UploadAsset200Response</returns>
        UploadAsset200Response DeleteWebhookSubscription(Guid id);

        /// <summary>
        /// Revoke a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        ApiResponse<UploadAsset200Response> DeleteWebhookSubscriptionWithHttpInfo(Guid id);
        /// <summary>
        /// List webhook subscriptions
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListWebhookSubscriptions200Response</returns>
        ListWebhookSubscriptions200Response ListWebhookSubscriptions();

        /// <summary>
        /// List webhook subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListWebhookSubscriptions200Response</returns>
        ApiResponse<ListWebhookSubscriptions200Response> ListWebhookSubscriptionsWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WebhookSubscription</returns>
        System.Threading.Tasks.Task<WebhookSubscription> CreateWebhookSubscriptionAsync(WebhookSubscriptionCreate webhookSubscriptionCreate, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WebhookSubscription)</returns>
        System.Threading.Tasks.Task<ApiResponse<WebhookSubscription>> CreateWebhookSubscriptionWithHttpInfoAsync(WebhookSubscriptionCreate webhookSubscriptionCreate, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Revoke a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        System.Threading.Tasks.Task<UploadAsset200Response> DeleteWebhookSubscriptionAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Revoke a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UploadAsset200Response>> DeleteWebhookSubscriptionWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List webhook subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListWebhookSubscriptions200Response</returns>
        System.Threading.Tasks.Task<ListWebhookSubscriptions200Response> ListWebhookSubscriptionsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List webhook subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListWebhookSubscriptions200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListWebhookSubscriptions200Response>> ListWebhookSubscriptionsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApi : IWebhooksApiSync, IWebhooksApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WebhooksApi : IDisposable, IWebhooksApi
    {
        private iLoveVideoEditor.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public WebhooksApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public WebhooksApi(string basePath)
        {
            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public WebhooksApi(iLoveVideoEditor.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebhooksApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebhooksApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                new iLoveVideoEditor.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebhooksApi(HttpClient client, iLoveVideoEditor.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = iLoveVideoEditor.Sdk.Client.Configuration.MergeConfigurations(
                iLoveVideoEditor.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new iLoveVideoEditor.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public WebhooksApi(iLoveVideoEditor.Sdk.Client.ISynchronousClient client, iLoveVideoEditor.Sdk.Client.IAsynchronousClient asyncClient, iLoveVideoEditor.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = iLoveVideoEditor.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public iLoveVideoEditor.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public iLoveVideoEditor.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <returns>WebhookSubscription</returns>
        public WebhookSubscription CreateWebhookSubscription(WebhookSubscriptionCreate webhookSubscriptionCreate)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<WebhookSubscription> localVarResponse = CreateWebhookSubscriptionWithHttpInfo(webhookSubscriptionCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <returns>ApiResponse of WebhookSubscription</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<WebhookSubscription> CreateWebhookSubscriptionWithHttpInfo(WebhookSubscriptionCreate webhookSubscriptionCreate)
        {
            // verify the required parameter 'webhookSubscriptionCreate' is set
            if (webhookSubscriptionCreate == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'webhookSubscriptionCreate' when calling WebhooksApi->CreateWebhookSubscription");

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = webhookSubscriptionCreate;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<WebhookSubscription>("/v1/webhooks", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateWebhookSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WebhookSubscription</returns>
        public async System.Threading.Tasks.Task<WebhookSubscription> CreateWebhookSubscriptionAsync(WebhookSubscriptionCreate webhookSubscriptionCreate, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<WebhookSubscription> localVarResponse = await CreateWebhookSubscriptionWithHttpInfoAsync(webhookSubscriptionCreate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookSubscriptionCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WebhookSubscription)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<WebhookSubscription>> CreateWebhookSubscriptionWithHttpInfoAsync(WebhookSubscriptionCreate webhookSubscriptionCreate, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'webhookSubscriptionCreate' is set
            if (webhookSubscriptionCreate == null)
                throw new iLoveVideoEditor.Sdk.Client.ApiException(400, "Missing required parameter 'webhookSubscriptionCreate' when calling WebhooksApi->CreateWebhookSubscription");


            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = webhookSubscriptionCreate;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<WebhookSubscription>("/v1/webhooks", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateWebhookSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>UploadAsset200Response</returns>
        public UploadAsset200Response DeleteWebhookSubscription(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = DeleteWebhookSubscriptionWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of UploadAsset200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> DeleteWebhookSubscriptionWithHttpInfo(Guid id)
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<UploadAsset200Response>("/v1/webhooks/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteWebhookSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UploadAsset200Response</returns>
        public async System.Threading.Tasks.Task<UploadAsset200Response> DeleteWebhookSubscriptionAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response> localVarResponse = await DeleteWebhookSubscriptionWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke a webhook subscription 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UploadAsset200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<UploadAsset200Response>> DeleteWebhookSubscriptionWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", iLoveVideoEditor.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<UploadAsset200Response>("/v1/webhooks/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteWebhookSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List webhook subscriptions 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListWebhookSubscriptions200Response</returns>
        public ListWebhookSubscriptions200Response ListWebhookSubscriptions()
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListWebhookSubscriptions200Response> localVarResponse = ListWebhookSubscriptionsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List webhook subscriptions 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListWebhookSubscriptions200Response</returns>
        public iLoveVideoEditor.Sdk.Client.ApiResponse<ListWebhookSubscriptions200Response> ListWebhookSubscriptionsWithHttpInfo()
        {
            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListWebhookSubscriptions200Response>("/v1/webhooks", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListWebhookSubscriptions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List webhook subscriptions 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListWebhookSubscriptions200Response</returns>
        public async System.Threading.Tasks.Task<ListWebhookSubscriptions200Response> ListWebhookSubscriptionsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            iLoveVideoEditor.Sdk.Client.ApiResponse<ListWebhookSubscriptions200Response> localVarResponse = await ListWebhookSubscriptionsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List webhook subscriptions 
        /// </summary>
        /// <exception cref="iLoveVideoEditor.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListWebhookSubscriptions200Response)</returns>
        public async System.Threading.Tasks.Task<iLoveVideoEditor.Sdk.Client.ApiResponse<ListWebhookSubscriptions200Response>> ListWebhookSubscriptionsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            iLoveVideoEditor.Sdk.Client.RequestOptions localVarRequestOptions = new iLoveVideoEditor.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = iLoveVideoEditor.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListWebhookSubscriptions200Response>("/v1/webhooks", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListWebhookSubscriptions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
