/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using iLoveVideoEditor.Sdk.Client;
using iLoveVideoEditor.Sdk.Api;
// uncomment below to import models
//using iLoveVideoEditor.Sdk.Model;

namespace iLoveVideoEditor.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing APIKeysApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class APIKeysApiTests : IDisposable
    {
        private APIKeysApi instance;

        public APIKeysApiTests()
        {
            instance = new APIKeysApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of APIKeysApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' APIKeysApi
            //Assert.IsType<APIKeysApi>(instance);
        }

        /// <summary>
        /// Test CreateApiKey
        /// </summary>
        [Fact]
        public void CreateApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateApiKeyRequest createApiKeyRequest = null;
            //var response = instance.CreateApiKey(createApiKeyRequest);
            //Assert.IsType<ApiKeyWithSecret>(response);
        }

        /// <summary>
        /// Test DeleteApiKey
        /// </summary>
        [Fact]
        public void DeleteApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.DeleteApiKey(id);
            //Assert.IsType<UploadAsset200Response>(response);
        }

        /// <summary>
        /// Test ListApiKeys
        /// </summary>
        [Fact]
        public void ListApiKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListApiKeys();
            //Assert.IsType<ListApiKeys200Response>(response);
        }
    }
}
