/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using iLoveVideoEditor.Sdk.Client;
using iLoveVideoEditor.Sdk.Api;
// uncomment below to import models
//using iLoveVideoEditor.Sdk.Model;

namespace iLoveVideoEditor.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing TemplatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TemplatesApiTests : IDisposable
    {
        private TemplatesApi instance;

        public TemplatesApiTests()
        {
            instance = new TemplatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TemplatesApi
            //Assert.IsType<TemplatesApi>(instance);
        }

        /// <summary>
        /// Test GetTemplate
        /// </summary>
        [Fact]
        public void GetTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetTemplate(id);
            //Assert.IsType<GetTemplate200Response>(response);
        }

        /// <summary>
        /// Test ListTemplates
        /// </summary>
        [Fact]
        public void ListTemplatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListTemplates();
            //Assert.IsType<ListTemplates200Response>(response);
        }

        /// <summary>
        /// Test RenderTemplate
        /// </summary>
        [Fact]
        public void RenderTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //RenderTemplateRequest renderTemplateRequest = null;
            //string? idempotencyKey = null;
            //var response = instance.RenderTemplate(id, renderTemplateRequest, idempotencyKey);
            //Assert.IsType<QueueRender200Response>(response);
        }
    }
}
