/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// ApiKeyWithSecret
    /// </summary>
    [DataContract(Name = "ApiKeyWithSecret")]
    public partial class ApiKeyWithSecret : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeyWithSecret" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiKeyWithSecret() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeyWithSecret" /> class.
        /// </summary>
        /// <param name="key">Full API key secret. Shown only once on creation. (required).</param>
        /// <param name="keyData">keyData (required).</param>
        public ApiKeyWithSecret(string key = default, ApiKey keyData = default)
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for ApiKeyWithSecret and cannot be null");
            }
            this.Key = key;
            // to ensure "keyData" is required (not null)
            if (keyData == null)
            {
                throw new ArgumentNullException("keyData is a required property for ApiKeyWithSecret and cannot be null");
            }
            this.KeyData = keyData;
        }

        /// <summary>
        /// Full API key secret. Shown only once on creation.
        /// </summary>
        /// <value>Full API key secret. Shown only once on creation.</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets KeyData
        /// </summary>
        [DataMember(Name = "keyData", IsRequired = true, EmitDefaultValue = true)]
        public ApiKey KeyData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiKeyWithSecret {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  KeyData: ").Append(KeyData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
