/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// ProjectUpdate
    /// </summary>
    [DataContract(Name = "ProjectUpdate")]
    public partial class ProjectUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectUpdate" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="videoJson">videoJson.</param>
        /// <param name="thumbnailUrl">thumbnailUrl.</param>
        /// <param name="thumbnailBase64">Base64-encoded thumbnail image. Uploaded to Bunny Storage..</param>
        /// <param name="spriteUrl">spriteUrl.</param>
        /// <param name="spriteBase64">Base64-encoded sprite sheet. Uploaded to Bunny Storage..</param>
        /// <param name="lastOpenedAt">lastOpenedAt.</param>
        /// <param name="duration">duration.</param>
        /// <param name="width">width.</param>
        /// <param name="height">height.</param>
        public ProjectUpdate(string name = default, string description = default, Object videoJson = default, string thumbnailUrl = default, string thumbnailBase64 = default, string spriteUrl = default, string spriteBase64 = default, DateTime lastOpenedAt = default, int duration = default, int width = default, int height = default)
        {
            this.Name = name;
            this.Description = description;
            this.VideoJson = videoJson;
            this.ThumbnailUrl = thumbnailUrl;
            this.ThumbnailBase64 = thumbnailBase64;
            this.SpriteUrl = spriteUrl;
            this.SpriteBase64 = spriteBase64;
            this.LastOpenedAt = lastOpenedAt;
            this.Duration = duration;
            this.Width = width;
            this.Height = height;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets VideoJson
        /// </summary>
        [DataMember(Name = "video_json", EmitDefaultValue = false)]
        public Object VideoJson { get; set; }

        /// <summary>
        /// Gets or Sets ThumbnailUrl
        /// </summary>
        [DataMember(Name = "thumbnail_url", EmitDefaultValue = false)]
        public string ThumbnailUrl { get; set; }

        /// <summary>
        /// Base64-encoded thumbnail image. Uploaded to Bunny Storage.
        /// </summary>
        /// <value>Base64-encoded thumbnail image. Uploaded to Bunny Storage.</value>
        [DataMember(Name = "thumbnail_base64", EmitDefaultValue = false)]
        public string ThumbnailBase64 { get; set; }

        /// <summary>
        /// Gets or Sets SpriteUrl
        /// </summary>
        [DataMember(Name = "sprite_url", EmitDefaultValue = false)]
        public string SpriteUrl { get; set; }

        /// <summary>
        /// Base64-encoded sprite sheet. Uploaded to Bunny Storage.
        /// </summary>
        /// <value>Base64-encoded sprite sheet. Uploaded to Bunny Storage.</value>
        [DataMember(Name = "sprite_base64", EmitDefaultValue = false)]
        public string SpriteBase64 { get; set; }

        /// <summary>
        /// Gets or Sets LastOpenedAt
        /// </summary>
        [DataMember(Name = "last_opened_at", EmitDefaultValue = false)]
        public DateTime LastOpenedAt { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", EmitDefaultValue = false)]
        public int Duration { get; set; }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", EmitDefaultValue = false)]
        public int Width { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", EmitDefaultValue = false)]
        public int Height { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectUpdate {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  VideoJson: ").Append(VideoJson).Append("\n");
            sb.Append("  ThumbnailUrl: ").Append(ThumbnailUrl).Append("\n");
            sb.Append("  ThumbnailBase64: ").Append(ThumbnailBase64).Append("\n");
            sb.Append("  SpriteUrl: ").Append(SpriteUrl).Append("\n");
            sb.Append("  SpriteBase64: ").Append(SpriteBase64).Append("\n");
            sb.Append("  LastOpenedAt: ").Append(LastOpenedAt).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
