/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// RenderCostEstimate
    /// </summary>
    [DataContract(Name = "RenderCostEstimate")]
    public partial class RenderCostEstimate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderCostEstimate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RenderCostEstimate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderCostEstimate" /> class.
        /// </summary>
        /// <param name="cost">Estimated credit cost. (required).</param>
        /// <param name="estimatedDuration">Duration in seconds. (required).</param>
        /// <param name="resolution">resolution (required).</param>
        /// <param name="fps">fps (required).</param>
        /// <param name="tier">tier.</param>
        public RenderCostEstimate(decimal cost = default, decimal estimatedDuration = default, RenderCostEstimateResolution resolution = default, int fps = default, RenderCostEstimateTier tier = default)
        {
            this.Cost = cost;
            this.EstimatedDuration = estimatedDuration;
            // to ensure "resolution" is required (not null)
            if (resolution == null)
            {
                throw new ArgumentNullException("resolution is a required property for RenderCostEstimate and cannot be null");
            }
            this.Resolution = resolution;
            this.Fps = fps;
            this.Tier = tier;
        }

        /// <summary>
        /// Estimated credit cost.
        /// </summary>
        /// <value>Estimated credit cost.</value>
        [DataMember(Name = "cost", IsRequired = true, EmitDefaultValue = true)]
        public decimal Cost { get; set; }

        /// <summary>
        /// Duration in seconds.
        /// </summary>
        /// <value>Duration in seconds.</value>
        [DataMember(Name = "estimatedDuration", IsRequired = true, EmitDefaultValue = true)]
        public decimal EstimatedDuration { get; set; }

        /// <summary>
        /// Gets or Sets Resolution
        /// </summary>
        [DataMember(Name = "resolution", IsRequired = true, EmitDefaultValue = true)]
        public RenderCostEstimateResolution Resolution { get; set; }

        /// <summary>
        /// Gets or Sets Fps
        /// </summary>
        [DataMember(Name = "fps", IsRequired = true, EmitDefaultValue = true)]
        public int Fps { get; set; }

        /// <summary>
        /// Gets or Sets Tier
        /// </summary>
        [DataMember(Name = "tier", EmitDefaultValue = true)]
        public RenderCostEstimateTier Tier { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenderCostEstimate {\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  EstimatedDuration: ").Append(EstimatedDuration).Append("\n");
            sb.Append("  Resolution: ").Append(Resolution).Append("\n");
            sb.Append("  Fps: ").Append(Fps).Append("\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
