/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// Rendition
    /// </summary>
    [DataContract(Name = "Rendition")]
    public partial class Rendition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rendition" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="jobId">jobId.</param>
        /// <param name="projectId">projectId.</param>
        /// <param name="status">status.</param>
        /// <param name="stage">stage.</param>
        /// <param name="cost">cost.</param>
        /// <param name="duration">duration.</param>
        /// <param name="width">width.</param>
        /// <param name="height">height.</param>
        /// <param name="fps">fps.</param>
        /// <param name="outputUrl">outputUrl.</param>
        /// <param name="outputSizeBytes">outputSizeBytes.</param>
        /// <param name="error">error.</param>
        /// <param name="progressPercent">progressPercent.</param>
        /// <param name="spriteUrl">spriteUrl.</param>
        /// <param name="videoJson">videoJson.</param>
        /// <param name="outputs">outputs.</param>
        /// <param name="projects">projects.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="completedAt">completedAt.</param>
        public Rendition(Guid id = default, string jobId = default, Guid? projectId = default, string status = default, string stage = default, decimal? cost = default, decimal? duration = default, int? width = default, int? height = default, int? fps = default, string outputUrl = default, int? outputSizeBytes = default, string error = default, int? progressPercent = default, string spriteUrl = default, Object videoJson = default, List<RenditionOutput> outputs = default, Object projects = default, DateTime createdAt = default, DateTime? completedAt = default)
        {
            this.Id = id;
            this.JobId = jobId;
            this.ProjectId = projectId;
            this.Status = status;
            this.Stage = stage;
            this.Cost = cost;
            this.Duration = duration;
            this.Width = width;
            this.Height = height;
            this.Fps = fps;
            this.OutputUrl = outputUrl;
            this.OutputSizeBytes = outputSizeBytes;
            this.Error = error;
            this.ProgressPercent = progressPercent;
            this.SpriteUrl = spriteUrl;
            this.VideoJson = videoJson;
            this.Outputs = outputs;
            this.Projects = projects;
            this.CreatedAt = createdAt;
            this.CompletedAt = completedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [DataMember(Name = "job_id", EmitDefaultValue = true)]
        public string JobId { get; set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [DataMember(Name = "project_id", EmitDefaultValue = true)]
        public Guid? ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [DataMember(Name = "stage", EmitDefaultValue = false)]
        public string Stage { get; set; }

        /// <summary>
        /// Gets or Sets Cost
        /// </summary>
        [DataMember(Name = "cost", EmitDefaultValue = true)]
        public decimal? Cost { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public decimal? Duration { get; set; }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", EmitDefaultValue = true)]
        public int? Width { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", EmitDefaultValue = true)]
        public int? Height { get; set; }

        /// <summary>
        /// Gets or Sets Fps
        /// </summary>
        [DataMember(Name = "fps", EmitDefaultValue = true)]
        public int? Fps { get; set; }

        /// <summary>
        /// Gets or Sets OutputUrl
        /// </summary>
        [DataMember(Name = "output_url", EmitDefaultValue = true)]
        public string OutputUrl { get; set; }

        /// <summary>
        /// Gets or Sets OutputSizeBytes
        /// </summary>
        [DataMember(Name = "output_size_bytes", EmitDefaultValue = true)]
        public int? OutputSizeBytes { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = true)]
        public string Error { get; set; }

        /// <summary>
        /// Gets or Sets ProgressPercent
        /// </summary>
        [DataMember(Name = "progress_percent", EmitDefaultValue = true)]
        public int? ProgressPercent { get; set; }

        /// <summary>
        /// Gets or Sets SpriteUrl
        /// </summary>
        [DataMember(Name = "sprite_url", EmitDefaultValue = true)]
        public string SpriteUrl { get; set; }

        /// <summary>
        /// Gets or Sets VideoJson
        /// </summary>
        [DataMember(Name = "video_json", EmitDefaultValue = true)]
        public Object VideoJson { get; set; }

        /// <summary>
        /// Gets or Sets Outputs
        /// </summary>
        [DataMember(Name = "outputs", EmitDefaultValue = false)]
        public List<RenditionOutput> Outputs { get; set; }

        /// <summary>
        /// Gets or Sets Projects
        /// </summary>
        [DataMember(Name = "projects", EmitDefaultValue = true)]
        public Object Projects { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [DataMember(Name = "completed_at", EmitDefaultValue = true)]
        public DateTime? CompletedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rendition {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Fps: ").Append(Fps).Append("\n");
            sb.Append("  OutputUrl: ").Append(OutputUrl).Append("\n");
            sb.Append("  OutputSizeBytes: ").Append(OutputSizeBytes).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  ProgressPercent: ").Append(ProgressPercent).Append("\n");
            sb.Append("  SpriteUrl: ").Append(SpriteUrl).Append("\n");
            sb.Append("  VideoJson: ").Append(VideoJson).Append("\n");
            sb.Append("  Outputs: ").Append(Outputs).Append("\n");
            sb.Append("  Projects: ").Append(Projects).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
