/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// Portable video scene definition produced by &#x60;@ilovevideoeditor/core&#x60;. The first layer must be a &#x60;composition&#x60; layer containing project settings (&#x60;width&#x60;, &#x60;height&#x60;, &#x60;fps&#x60;, &#x60;sourceDuration&#x60;, …).
    /// </summary>
    [DataContract(Name = "VideoJSON")]
    public partial class VideoJSON : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoJSON" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VideoJSON()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoJSON" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="layers">layers (required).</param>
        /// <param name="tracks">tracks.</param>
        /// <param name="destinations">Optional output destinations for this render. Each entry references a workspace integration by ID; the API resolves credentials server-side..</param>
        public VideoJSON(string name = default, List<Object> layers = default, List<Object> tracks = default, List<VideoJSONDestination> destinations = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for VideoJSON and cannot be null");
            }
            this.Name = name;
            // to ensure "layers" is required (not null)
            if (layers == null)
            {
                throw new ArgumentNullException("layers is a required property for VideoJSON and cannot be null");
            }
            this.Layers = layers;
            this.Tracks = tracks;
            this.Destinations = destinations;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Layers
        /// </summary>
        [DataMember(Name = "layers", IsRequired = true, EmitDefaultValue = true)]
        public List<Object> Layers { get; set; }

        /// <summary>
        /// Gets or Sets Tracks
        /// </summary>
        [DataMember(Name = "tracks", EmitDefaultValue = false)]
        public List<Object> Tracks { get; set; }

        /// <summary>
        /// Optional output destinations for this render. Each entry references a workspace integration by ID; the API resolves credentials server-side.
        /// </summary>
        /// <value>Optional output destinations for this render. Each entry references a workspace integration by ID; the API resolves credentials server-side.</value>
        [DataMember(Name = "destinations", EmitDefaultValue = false)]
        public List<VideoJSONDestination> Destinations { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VideoJSON {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Layers: ").Append(Layers).Append("\n");
            sb.Append("  Tracks: ").Append(Tracks).Append("\n");
            sb.Append("  Destinations: ").Append(Destinations).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 200.", new [] { "Name" });
            }

            yield break;
        }
    }

}
