/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// Reference to a workspace storage integration where the rendered video should be delivered. Credentials are never stored here.
    /// </summary>
    [DataContract(Name = "VideoJSONDestination")]
    public partial class VideoJSONDestination : IValidatableObject
    {
        /// <summary>
        /// Storage provider the integration is configured for.
        /// </summary>
        /// <value>Storage provider the integration is configured for.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProviderEnum
        {
            /// <summary>
            /// Enum S3 for value: s3
            /// </summary>
            [EnumMember(Value = "s3")]
            S3 = 1,

            /// <summary>
            /// Enum R2 for value: r2
            /// </summary>
            [EnumMember(Value = "r2")]
            R2 = 2,

            /// <summary>
            /// Enum B2 for value: b2
            /// </summary>
            [EnumMember(Value = "b2")]
            B2 = 3,

            /// <summary>
            /// Enum Wasabi for value: wasabi
            /// </summary>
            [EnumMember(Value = "wasabi")]
            Wasabi = 4,

            /// <summary>
            /// Enum Gcs for value: gcs
            /// </summary>
            [EnumMember(Value = "gcs")]
            Gcs = 5,

            /// <summary>
            /// Enum Azure for value: azure
            /// </summary>
            [EnumMember(Value = "azure")]
            Azure = 6,

            /// <summary>
            /// Enum Drive for value: drive
            /// </summary>
            [EnumMember(Value = "drive")]
            Drive = 7
        }


        /// <summary>
        /// Storage provider the integration is configured for.
        /// </summary>
        /// <value>Storage provider the integration is configured for.</value>
        [DataMember(Name = "provider", IsRequired = true, EmitDefaultValue = true)]
        public ProviderEnum Provider { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoJSONDestination" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VideoJSONDestination() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoJSONDestination" /> class.
        /// </summary>
        /// <param name="integrationId">Workspace integration identifier. (required).</param>
        /// <param name="provider">Storage provider the integration is configured for. (required).</param>
        /// <param name="pathPrefix">Optional path prefix override for this render..</param>
        public VideoJSONDestination(string integrationId = default, ProviderEnum provider = default, string pathPrefix = default)
        {
            // to ensure "integrationId" is required (not null)
            if (integrationId == null)
            {
                throw new ArgumentNullException("integrationId is a required property for VideoJSONDestination and cannot be null");
            }
            this.IntegrationId = integrationId;
            this.Provider = provider;
            this.PathPrefix = pathPrefix;
        }

        /// <summary>
        /// Workspace integration identifier.
        /// </summary>
        /// <value>Workspace integration identifier.</value>
        [DataMember(Name = "integrationId", IsRequired = true, EmitDefaultValue = true)]
        public string IntegrationId { get; set; }

        /// <summary>
        /// Optional path prefix override for this render.
        /// </summary>
        /// <value>Optional path prefix override for this render.</value>
        [DataMember(Name = "pathPrefix", EmitDefaultValue = false)]
        public string PathPrefix { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VideoJSONDestination {\n");
            sb.Append("  IntegrationId: ").Append(IntegrationId).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  PathPrefix: ").Append(PathPrefix).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
