/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// WorkspaceIntegration
    /// </summary>
    [DataContract(Name = "WorkspaceIntegration")]
    public partial class WorkspaceIntegration : IValidatableObject
    {
        /// <summary>
        /// Defines Provider
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProviderEnum
        {
            /// <summary>
            /// Enum S3 for value: s3
            /// </summary>
            [EnumMember(Value = "s3")]
            S3 = 1,

            /// <summary>
            /// Enum R2 for value: r2
            /// </summary>
            [EnumMember(Value = "r2")]
            R2 = 2,

            /// <summary>
            /// Enum B2 for value: b2
            /// </summary>
            [EnumMember(Value = "b2")]
            B2 = 3,

            /// <summary>
            /// Enum Wasabi for value: wasabi
            /// </summary>
            [EnumMember(Value = "wasabi")]
            Wasabi = 4,

            /// <summary>
            /// Enum Gcs for value: gcs
            /// </summary>
            [EnumMember(Value = "gcs")]
            Gcs = 5,

            /// <summary>
            /// Enum Azure for value: azure
            /// </summary>
            [EnumMember(Value = "azure")]
            Azure = 6,

            /// <summary>
            /// Enum Drive for value: drive
            /// </summary>
            [EnumMember(Value = "drive")]
            Drive = 7
        }


        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [DataMember(Name = "provider", IsRequired = true, EmitDefaultValue = true)]
        public ProviderEnum Provider { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceIntegration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkspaceIntegration() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceIntegration" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="workspaceId">workspaceId (required).</param>
        /// <param name="provider">provider (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="isActive">isActive (required).</param>
        /// <param name="isDefault">isDefault (required).</param>
        /// <param name="config">config (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public WorkspaceIntegration(Guid id = default, Guid workspaceId = default, ProviderEnum provider = default, string name = default, bool isActive = default, bool isDefault = default, Dictionary<string, Object> config = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            this.Id = id;
            this.WorkspaceId = workspaceId;
            this.Provider = provider;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for WorkspaceIntegration and cannot be null");
            }
            this.Name = name;
            this.IsActive = isActive;
            this.IsDefault = isDefault;
            // to ensure "config" is required (not null)
            if (config == null)
            {
                throw new ArgumentNullException("config is a required property for WorkspaceIntegration and cannot be null");
            }
            this.Config = config;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets WorkspaceId
        /// </summary>
        [DataMember(Name = "workspaceId", IsRequired = true, EmitDefaultValue = true)]
        public Guid WorkspaceId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets IsDefault
        /// </summary>
        [DataMember(Name = "isDefault", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDefault { get; set; }

        /// <summary>
        /// Gets or Sets Config
        /// </summary>
        [DataMember(Name = "config", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Config { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkspaceIntegration {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  WorkspaceId: ").Append(WorkspaceId).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsDefault: ").Append(IsDefault).Append("\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
