/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = iLoveVideoEditor.Sdk.Client.FileParameter;
using OpenAPIDateConverter = iLoveVideoEditor.Sdk.Client.OpenAPIDateConverter;

namespace iLoveVideoEditor.Sdk.Model
{
    /// <summary>
    /// WorkflowStep
    /// </summary>
    [DataContract(Name = "WorkflowStep")]
    public partial class WorkflowStep : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum UploadAsset for value: upload_asset
            /// </summary>
            [EnumMember(Value = "upload_asset")]
            UploadAsset = 1,

            /// <summary>
            /// Enum CrawlUrl for value: crawl_url
            /// </summary>
            [EnumMember(Value = "crawl_url")]
            CrawlUrl = 2,

            /// <summary>
            /// Enum DiscoverVariables for value: discover_variables
            /// </summary>
            [EnumMember(Value = "discover_variables")]
            DiscoverVariables = 3,

            /// <summary>
            /// Enum RenderTemplate for value: render_template
            /// </summary>
            [EnumMember(Value = "render_template")]
            RenderTemplate = 4,

            /// <summary>
            /// Enum RenderVideojson for value: render_videojson
            /// </summary>
            [EnumMember(Value = "render_videojson")]
            RenderVideojson = 5,

            /// <summary>
            /// Enum ApplyTool for value: apply_tool
            /// </summary>
            [EnumMember(Value = "apply_tool")]
            ApplyTool = 6,

            /// <summary>
            /// Enum Review for value: review
            /// </summary>
            [EnumMember(Value = "review")]
            Review = 7,

            /// <summary>
            /// Enum SendToDestination for value: send_to_destination
            /// </summary>
            [EnumMember(Value = "send_to_destination")]
            SendToDestination = 8
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStep" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowStep() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStep" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="name">name.</param>
        /// <param name="maxRetries">maxRetries.</param>
        /// <param name="config">config (required).</param>
        public WorkflowStep(TypeEnum type = default, string name = default, int maxRetries = default, Dictionary<string, Object> config = default)
        {
            this.Type = type;
            // to ensure "config" is required (not null)
            if (config == null)
            {
                throw new ArgumentNullException("config is a required property for WorkflowStep and cannot be null");
            }
            this.Config = config;
            this.Name = name;
            this.MaxRetries = maxRetries;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets MaxRetries
        /// </summary>
        [DataMember(Name = "maxRetries", EmitDefaultValue = false)]
        public int MaxRetries { get; set; }

        /// <summary>
        /// Gets or Sets Config
        /// </summary>
        [DataMember(Name = "config", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Config { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowStep {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  MaxRetries: ").Append(MaxRetries).Append("\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaxRetries (int) maximum
            if (this.MaxRetries > (int)10)
            {
                yield return new ValidationResult("Invalid value for MaxRetries, must be a value less than or equal to 10.", new [] { "MaxRetries" });
            }

            // MaxRetries (int) minimum
            if (this.MaxRetries < (int)0)
            {
                yield return new ValidationResult("Invalid value for MaxRetries, must be a value greater than or equal to 0.", new [] { "MaxRetries" });
            }

            yield break;
        }
    }

}
