/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iLoveVideoEditor.Sdk.Model;
using iLoveVideoEditor.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iLoveVideoEditor.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApiKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiKeyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiKey
        //private ApiKey instance;

        public ApiKeyTests()
        {
            // TODO uncomment below to create an instance of ApiKey
            //instance = new ApiKey();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiKey
        /// </summary>
        [Fact]
        public void ApiKeyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiKey
            //Assert.IsType<ApiKey>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'KeyPrefix'
        /// </summary>
        [Fact]
        public void KeyPrefixTest()
        {
            // TODO unit test for the property 'KeyPrefix'
        }

        /// <summary>
        /// Test the property 'LastUsedAt'
        /// </summary>
        [Fact]
        public void LastUsedAtTest()
        {
            // TODO unit test for the property 'LastUsedAt'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'RevokedAt'
        /// </summary>
        [Fact]
        public void RevokedAtTest()
        {
            // TODO unit test for the property 'RevokedAt'
        }
    }
}
