/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iLoveVideoEditor.Sdk.Model;
using iLoveVideoEditor.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iLoveVideoEditor.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BillingSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillingSubscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BillingSubscription
        //private BillingSubscription instance;

        public BillingSubscriptionTests()
        {
            // TODO uncomment below to create an instance of BillingSubscription
            //instance = new BillingSubscription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillingSubscription
        /// </summary>
        [Fact]
        public void BillingSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" BillingSubscription
            //Assert.IsType<BillingSubscription>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CurrentPeriodEnd'
        /// </summary>
        [Fact]
        public void CurrentPeriodEndTest()
        {
            // TODO unit test for the property 'CurrentPeriodEnd'
        }

        /// <summary>
        /// Test the property 'CreditsBalance'
        /// </summary>
        [Fact]
        public void CreditsBalanceTest()
        {
            // TODO unit test for the property 'CreditsBalance'
        }

        /// <summary>
        /// Test the property 'CreditsTotal'
        /// </summary>
        [Fact]
        public void CreditsTotalTest()
        {
            // TODO unit test for the property 'CreditsTotal'
        }

        /// <summary>
        /// Test the property 'Tier'
        /// </summary>
        [Fact]
        public void TierTest()
        {
            // TODO unit test for the property 'Tier'
        }
    }
}
