/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iLoveVideoEditor.Sdk.Model;
using iLoveVideoEditor.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iLoveVideoEditor.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreditBalanceSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditBalanceSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditBalanceSummary
        //private CreditBalanceSummary instance;

        public CreditBalanceSummaryTests()
        {
            // TODO uncomment below to create an instance of CreditBalanceSummary
            //instance = new CreditBalanceSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditBalanceSummary
        /// </summary>
        [Fact]
        public void CreditBalanceSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreditBalanceSummary
            //Assert.IsType<CreditBalanceSummary>(instance);
        }

        /// <summary>
        /// Test the property 'Purchased'
        /// </summary>
        [Fact]
        public void PurchasedTest()
        {
            // TODO unit test for the property 'Purchased'
        }

        /// <summary>
        /// Test the property 'Consumed'
        /// </summary>
        [Fact]
        public void ConsumedTest()
        {
            // TODO unit test for the property 'Consumed'
        }

        /// <summary>
        /// Test the property 'Refunded'
        /// </summary>
        [Fact]
        public void RefundedTest()
        {
            // TODO unit test for the property 'Refunded'
        }

        /// <summary>
        /// Test the property 'Consumed30Days'
        /// </summary>
        [Fact]
        public void Consumed30DaysTest()
        {
            // TODO unit test for the property 'Consumed30Days'
        }
    }
}
