/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iLoveVideoEditor.Sdk.Model;
using iLoveVideoEditor.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iLoveVideoEditor.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProjectUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProjectUpdate
        //private ProjectUpdate instance;

        public ProjectUpdateTests()
        {
            // TODO uncomment below to create an instance of ProjectUpdate
            //instance = new ProjectUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectUpdate
        /// </summary>
        [Fact]
        public void ProjectUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProjectUpdate
            //Assert.IsType<ProjectUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'VideoJson'
        /// </summary>
        [Fact]
        public void VideoJsonTest()
        {
            // TODO unit test for the property 'VideoJson'
        }

        /// <summary>
        /// Test the property 'ThumbnailUrl'
        /// </summary>
        [Fact]
        public void ThumbnailUrlTest()
        {
            // TODO unit test for the property 'ThumbnailUrl'
        }

        /// <summary>
        /// Test the property 'ThumbnailBase64'
        /// </summary>
        [Fact]
        public void ThumbnailBase64Test()
        {
            // TODO unit test for the property 'ThumbnailBase64'
        }

        /// <summary>
        /// Test the property 'SpriteUrl'
        /// </summary>
        [Fact]
        public void SpriteUrlTest()
        {
            // TODO unit test for the property 'SpriteUrl'
        }

        /// <summary>
        /// Test the property 'SpriteBase64'
        /// </summary>
        [Fact]
        public void SpriteBase64Test()
        {
            // TODO unit test for the property 'SpriteBase64'
        }

        /// <summary>
        /// Test the property 'LastOpenedAt'
        /// </summary>
        [Fact]
        public void LastOpenedAtTest()
        {
            // TODO unit test for the property 'LastOpenedAt'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
    }
}
