/*
 * iLoveVideoEditor API
 *
 * Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iLoveVideoEditor.Sdk.Model;
using iLoveVideoEditor.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iLoveVideoEditor.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowRunStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowRunStepTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowRunStep
        //private WorkflowRunStep instance;

        public WorkflowRunStepTests()
        {
            // TODO uncomment below to create an instance of WorkflowRunStep
            //instance = new WorkflowRunStep();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowRunStep
        /// </summary>
        [Fact]
        public void WorkflowRunStepInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowRunStep
            //Assert.IsType<WorkflowRunStep>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'WorkflowRunId'
        /// </summary>
        [Fact]
        public void WorkflowRunIdTest()
        {
            // TODO unit test for the property 'WorkflowRunId'
        }

        /// <summary>
        /// Test the property 'StepIndex'
        /// </summary>
        [Fact]
        public void StepIndexTest()
        {
            // TODO unit test for the property 'StepIndex'
        }

        /// <summary>
        /// Test the property 'StepType'
        /// </summary>
        [Fact]
        public void StepTypeTest()
        {
            // TODO unit test for the property 'StepType'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'InputUrl'
        /// </summary>
        [Fact]
        public void InputUrlTest()
        {
            // TODO unit test for the property 'InputUrl'
        }

        /// <summary>
        /// Test the property 'OutputUrl'
        /// </summary>
        [Fact]
        public void OutputUrlTest()
        {
            // TODO unit test for the property 'OutputUrl'
        }

        /// <summary>
        /// Test the property 'OutputKey'
        /// </summary>
        [Fact]
        public void OutputKeyTest()
        {
            // TODO unit test for the property 'OutputKey'
        }

        /// <summary>
        /// Test the property 'RenditionId'
        /// </summary>
        [Fact]
        public void RenditionIdTest()
        {
            // TODO unit test for the property 'RenditionId'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'ResponseStatus'
        /// </summary>
        [Fact]
        public void ResponseStatusTest()
        {
            // TODO unit test for the property 'ResponseStatus'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'RetryCount'
        /// </summary>
        [Fact]
        public void RetryCountTest()
        {
            // TODO unit test for the property 'RetryCount'
        }

        /// <summary>
        /// Test the property 'MaxRetries'
        /// </summary>
        [Fact]
        public void MaxRetriesTest()
        {
            // TODO unit test for the property 'MaxRetries'
        }

        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
